- id: walrus-grep
  name: walrus-grep
  description: Warn about assignment expressions (pep572)
  entry: ":="
  language: pygrep
  types: [python]

- id: walrus-ast
  name: walrus-ast
  description: Warn about assignment expressions (pep572)
  entry: walrus-ast
  language: python
  types: [python]

- id: walrus-opportunity
  name: walrus-opportunity
  description: Warn about missed opportunity to use ":="
  entry: walrus-opportunity
  language: python
  types: [python]
