repos:
  - repo: https://github.com/gyermolenko/pre-commit-hooks
    rev: 34f2e54609272149466e00d54c8bbd0c4b2782fb
    hooks:
      - id: walrus-grep
      # - id: walrus-ast
        # language_version: python3.8
      - id: walrus-opportunity
        language_version: python3.7
